apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: storageclass-ssd
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
  fstype: ext4
  replication-type: none
allowVolumeExpansion: true
