apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: devops-kibana
  namespace: elk
spec:
  version: 7.7.1
  count: 3
  elasticsearchRef:
    name: devops-es-nodes
  http:
    service:
      metadata:
        annotations:
          cloud.google.com/load-balancer-type: Internal
      spec:
        type: LoadBalancer
        ports:
          - name: kibana-http
            port: 5601
            targetPort: 5601
    tls:
      selfSignedCertificate:
        disabled: true
  podTemplate:
    spec:
      containers:
      - name: kibana
        resources:
          requests:
            memory: 1Gi
            cpu: 0.5
          limits:
            memory: 2Gi
            cpu: 2
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: name
                operator: In
                values:
                - elk
