apiVersion: v1
kind: Service
metadata:
  namespace: devops-elasticsearch
  name: logstash
  labels:
    app: logstash
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
spec:
  type: LoadBalancer 
  ports:
    - port: 5044
      name: logstash
      targetPort: 5044
      protocol: TCP
    - port: 25826
      name: udp-logstash
      targetPort: 25826
      protocol: TCP
  selector:
    app: logstash